add to node.js
kinuesantos/garageScript pull request #2
Opened 2017-08-16 02:48 UTC by kinuesantos

2017-08-16 05:55 UTC, songz commented on lesson2/node.js
> +  console.log(files);
good start! Now implement part 2:
Print out all the file names that are not you :)

2017-08-17 00:47 UTC, allopez7 commented on lesson2/node.js
> +const f = require('fs');
add a more descriptive name for fs.

2017-08-17 00:48 UTC, allopez7 commented on lesson2/node.js
> +    files.forEach((e) => {
add a more descriptive name for e.

2017-08-17 00:49 UTC, allopez7 commented on lesson2/node.js
> +        names = '\n' + names + '\n' + e;
get rid of the first '\n', no need for a new line initially.

2017-08-17 00:49 UTC, allopez7 commented on lesson2/node.js
> +  console.log(notme());
get rid of this console and notme() funtion call.

2017-08-17 00:54 UTC, allopez7 requested changes
I would also suggest adding more spacing to make it easier to read.

2017-08-18 23:17 UTC, MadhuBeesetty approved these changes
try giving a bit relative variable names so that you wont get confused while you code.

2017-08-28 21:48 UTC, merged